# Generated by Django 4.2 on 2026-03-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("arithmetic", "Arithmetic"),
                            ("number_system", "Number System"),
                            ("algebra", "Algebra"),
                            ("geometry", "Geometry & Mensuration"),
                            ("modern_maths", "Modern Maths"),
                            ("time_speed_work", "Time, Speed & Work"),
                            ("data_interpretation", "Data Interpretation"),
                            ("logical_reasoning", "Logical Reasoning"),
                            ("verbal_ability", "Verbal Ability"),
                            ("computer_aptitude", "Computer Aptitude"),
                            ("general_aptitude", "General Aptitude"),
                        ],
                        default="arithmetic",
                        max_length=50,
                    ),
                ),
                ("icon", models.CharField(default="📘", max_length=10)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Beginner",
                        max_length=20,
                    ),
                ),
                (
                    "definition",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("wikipedia_url", models.URLField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TopicVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_id", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=300)),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                (
                    "channel_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("duration", models.CharField(blank=True, default="", max_length=20)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="learning.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("topic", "youtube_id")},
            },
        ),
    ]
