# Generated by Django 4.2 on 2026-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="has_quiz",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topic",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="topic",
            name="category",
            field=models.CharField(
                choices=[
                    ("arithmetic", "Arithmetic"),
                    ("number_system", "Number System"),
                    ("algebra", "Algebra"),
                    ("geometry", "Geometry & Mensuration"),
                    ("modern_maths", "Modern Maths"),
                    ("time_speed_work", "Time, Speed & Work"),
                    ("data_interpretation", "Data Interpretation"),
                    ("logical_reasoning", "Logical Reasoning"),
                    ("verbal_ability", "Verbal Ability"),
                    ("computer_aptitude", "Computer Aptitude"),
                    ("general_aptitude", "General Aptitude"),
                    ("quantitative", "Quantitative Aptitude"),
                ],
                default="arithmetic",
                max_length=50,
            ),
        ),
    ]
