# Generated by Django 4.2 on 2025-12-20 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="resumes/")),
                ("filename", models.CharField(blank=True, max_length=255)),
                (
                    "raw_text",
                    models.TextField(
                        blank=True, help_text="Full extracted text from resume"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        default=list, help_text="List of extracted skills"
                    ),
                ),
                (
                    "experience",
                    models.JSONField(default=list, help_text="Work experience entries"),
                ),
                (
                    "education",
                    models.JSONField(default=list, help_text="Education entries"),
                ),
                (
                    "projects",
                    models.JSONField(default=list, help_text="Project details"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated resume summary"
                    ),
                ),
                ("is_parsed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interview_resume",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("HR", "HR Interview"),
                            ("Technical", "Technical Interview"),
                            ("Behavioral", "Behavioral Interview"),
                            ("Mixed", "Mixed Interview"),
                        ],
                        default="Technical",
                        max_length=20,
                    ),
                ),
                ("total_questions", models.PositiveIntegerField(default=5)),
                ("duration_minutes", models.PositiveIntegerField(default=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_question_index", models.PositiveIntegerField(default=0)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "overall_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "communication_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "technical_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_sessions",
                        to="interview.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interview_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                ("question_number", models.PositiveIntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("situational", "Situational"),
                            ("problem_solving", "Problem Solving"),
                            ("communication", "Communication"),
                            ("teamwork", "Teamwork"),
                            ("leadership", "Leadership"),
                        ],
                        default="technical",
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Easy"),
                            (2, "Medium-Easy"),
                            (3, "Medium"),
                            (4, "Medium-Hard"),
                            (5, "Hard"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "context_used",
                    models.TextField(
                        blank=True,
                        help_text="Resume context used for question generation",
                    ),
                ),
                (
                    "expected_points",
                    models.JSONField(
                        default=list, help_text="Key points expected in a good answer"
                    ),
                ),
                ("suggested_time_seconds", models.PositiveIntegerField(default=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="interview.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "interview_question",
                "ordering": ["question_number"],
                "unique_together": {("session", "question_number")},
            },
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_summary",
                    models.TextField(
                        help_text="AI-generated summary of interview performance"
                    ),
                ),
                (
                    "overall_rating",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("average", "Average"),
                            ("needs_improvement", "Needs Improvement"),
                            ("poor", "Poor"),
                        ],
                        default="average",
                        max_length=20,
                    ),
                ),
                (
                    "strengths",
                    models.JSONField(
                        default=list, help_text="Overall strengths identified"
                    ),
                ),
                (
                    "weaknesses",
                    models.JSONField(
                        default=list, help_text="Areas needing improvement"
                    ),
                ),
                (
                    "suggestions",
                    models.JSONField(
                        default=list, help_text="Actionable improvement suggestions"
                    ),
                ),
                (
                    "topic_scores",
                    models.JSONField(
                        default=dict, help_text="Scores per topic/category"
                    ),
                ),
                (
                    "percentile",
                    models.FloatField(
                        blank=True,
                        help_text="Performance percentile compared to other users",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "recommended_resources",
                    models.JSONField(
                        default=list, help_text="Learning resources to improve"
                    ),
                ),
                (
                    "practice_areas",
                    models.JSONField(default=list, help_text="Topics to practice more"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="interview.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "interview_feedback",
            },
        ),
        migrations.CreateModel(
            name="InterviewAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.TextField()),
                (
                    "answer_duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "ai_feedback",
                    models.TextField(help_text="Detailed AI feedback on the answer"),
                ),
                (
                    "strengths",
                    models.JSONField(
                        default=list, help_text="List of strengths identified"
                    ),
                ),
                (
                    "improvements",
                    models.JSONField(default=list, help_text="Areas for improvement"),
                ),
                (
                    "key_points_covered",
                    models.JSONField(
                        default=list, help_text="Expected points that were covered"
                    ),
                ),
                (
                    "key_points_missed",
                    models.JSONField(
                        default=list, help_text="Expected points that were missed"
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "clarity_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "depth_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="interview.interviewquestion",
                    ),
                ),
            ],
            options={
                "db_table": "interview_answer",
            },
        ),
    ]
