# Generated by Django 4.2 on 2026-03-20 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="hr_avg_score",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_used",
                    models.CharField(
                        default="gemini-2.5-flash",
                        help_text="Gemini model used for this evaluation",
                        max_length=50,
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "hr_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "technical_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "communication_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "structure_score",
                    models.FloatField(
                        help_text="How well the candidate structured their answers",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "summary_feedback",
                    models.TextField(
                        help_text="4-5 sentence holistic assessment from Gemini"
                    ),
                ),
                (
                    "top_strength",
                    models.CharField(
                        help_text="Single biggest strength observed across the session",
                        max_length=400,
                    ),
                ),
                (
                    "top_weakness",
                    models.CharField(
                        help_text="Single most important area to improve",
                        max_length=400,
                    ),
                ),
                (
                    "top_3_recommendations",
                    models.TextField(
                        help_text="JSON array of three actionable next-step recommendations"
                    ),
                ),
                (
                    "placement_readiness",
                    models.CharField(
                        choices=[
                            ("not_ready", "Not Ready"),
                            ("needs_work", "Needs Work"),
                            ("almost_ready", "Almost Ready"),
                            ("ready", "Ready"),
                            ("highly_ready", "Highly Ready"),
                        ],
                        default="needs_work",
                        max_length=30,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="interview.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "interview_evaluation_result",
            },
        ),
    ]
